reduce events number in test
Signed-off-by: tnazarew <tomasz.nazarewicz@getindata.com>

diff --git a/.github/workflows/collect_and_compare_reports.yml b/.github/workflows/collect_and_compare_reports.yml
--- a/.github/workflows/collect_and_compare_reports.yml
+++ b/.github/workflows/collect_and_compare_reports.yml
@@ -54,9 +54,9 @@ jobs:
         run: |
           if [ -f reports/retention-failures-report.json ]; then
             echo "File exists."
-            echo "content: $(cat reports/retention-failures-report.json)
+            echo "content: $(cat reports/retention-failures-report.json)"
             echo "jq -e '. == []' reports/retention-failures-report.json result"
             echo "jq '. == []' reports/retention-failures-report.json"
           fi
 
-          jq -e '. == []' reports/retention-failures-report.json > /dev/null || { exit 1 }
+          jq -e '. == []' reports/retention-failures-report.json > /dev/null ||  exit 1
